In [41]:
# Load dataset

!git clone https://github.com/Aadi22204/personal-finance-intelligence.git

fatal: destination path 'personal-finance-intelligence' already exists and is not an empty directory.

In [42]:
# Load dataset
import pandas as pd
df=pd.read_csv("personal-finance-intelligence/data/transactions.csv")
df.head()

   id        date     type  category  amount     description
0   1  2026-09-01   Income    Salary   30000  Monthly salary
1   2  2026-09-02  Expense      Food     250           Lunch
2   3  2026-09-03  Expense    Travel     500  Cab to college
3   4  2026-09-04  Expense  Shopping    1200         Clothes
4   5  2026-09-05  Expense      Food     180       Breakfast

In [43]:
# select expenses
expenses = df[df["type"] == "Expense"].copy()

In [44]:
# create category budget
budgets = {
    "Food": 5000,
    "Shopping": 7000,
    "Travel": 5000,
    "Bills": 4000,
    "Education": 3000,
    "Entertainment": 3000,
    "Health": 2500
}

In [45]:
# Calculate actual spending
category_spending = expenses.groupby("category")['amount'].sum()
category_spending

category
Bills            3800
Education        2700
Entertainment    2250
Food             4500
Health           1950
Shopping         8750
Travel           4250
Name: amount, dtype: int64

In [46]:
# Create a budget table

budget_data = []

for category, budget in budgets.items():

    actual = category_spending.get(category, 0)

    remaining = budget - actual

    budget_data.append({
        "category": category,
        "budget": budget,
        "actual_spending": actual,
        "remaining": remaining
    })

budget_summary = pd.DataFrame(budget_data)

budget_summary

        category  budget  actual_spending  remaining
0           Food    5000             4500        500
1       Shopping    7000             8750      -1750
2         Travel    5000             4250        750
3          Bills    4000             3800        200
4      Education    3000             2700        300
5  Entertainment    3000             2250        750
6         Health    2500             1950        550

In [47]:
# Add budget status
budget_summary["status"] = budget_summary["remaining"].apply(
    lambda x: "Over Budget" if x < 0 else "Within Budget"
)
budget_summary

        category  budget  actual_spending  remaining         status
0           Food    5000             4500        500  Within Budget
1       Shopping    7000             8750      -1750    Over Budget
2         Travel    5000             4250        750  Within Budget
3          Bills    4000             3800        200  Within Budget
4      Education    3000             2700        300  Within Budget
5  Entertainment    3000             2250        750  Within Budget
6         Health    2500             1950        550  Within Budget

In [48]:
# Calculate budget utilization
budget_summary["utilization"] = (
    budget_summary["actual_spending"]
    / budget_summary["budget"]
) * 100

#  rount it
budget_summary["utilization"] = (
    budget_summary["utilization"].round(2)
)

In [49]:
# Find over-budget categories
over_budget = budget_summary[
    budget_summary["remaining"] < 0
]

print("Over Budget Categories")
print("----------------------")

print(over_budget)

Over Budget Categories
----------------------
   category  budget  actual_spending  remaining       status  utilization
1  Shopping    7000             8750      -1750  Over Budget        125.0

In [50]:
print("Budget Tracking Report")
print("----------------------")

for index, row in budget_summary.iterrows():

    print(
        f"{row['category']}: "
        f"Budget ₹{row['budget']} | "
        f"Spent ₹{row['actual_spending']} | "
        f"Used {row['utilization']}% | "
        f"{row['status']}"
    )

Budget Tracking Report
----------------------
Food: Budget ₹5000 | Spent ₹4500 | Used 90.0% | Within Budget
Shopping: Budget ₹7000 | Spent ₹8750 | Used 125.0% | Over Budget
Travel: Budget ₹5000 | Spent ₹4250 | Used 85.0% | Within Budget
Bills: Budget ₹4000 | Spent ₹3800 | Used 95.0% | Within Budget
Education: Budget ₹3000 | Spent ₹2700 | Used 90.0% | Within Budget
Entertainment: Budget ₹3000 | Spent ₹2250 | Used 75.0% | Within Budget
Health: Budget ₹2500 | Spent ₹1950 | Used 78.0% | Within Budget