In [67]:
# Load dataset

!git clone https://github.com/Aadi22204/personal-finance-intelligence.git

fatal: destination path 'personal-finance-intelligence' already exists and is not an empty directory.

In [68]:
# Load dataset

import pandas as pd
df = pd.read_csv("personal-finance-intelligence/data/transactions.csv")
df.head()

   id        date     type  category  amount     description
0   1  2026-09-01   Income    Salary   30000  Monthly salary
1   2  2026-09-02  Expense      Food     250           Lunch
2   3  2026-09-03  Expense    Travel     500  Cab to college
3   4  2026-09-04  Expense  Shopping    1200         Clothes
4   5  2026-09-05  Expense      Food     180       Breakfast

In [69]:
# convert date column
df['date']=pd.to_datetime(df['date'])
df.head()

   id       date     type  category  amount     description
0   1 2026-09-01   Income    Salary   30000  Monthly salary
1   2 2026-09-02  Expense      Food     250           Lunch
2   3 2026-09-03  Expense    Travel     500  Cab to college
3   4 2026-09-04  Expense  Shopping    1200         Clothes
4   5 2026-09-05  Expense      Food     180       Breakfast

In [70]:
# selecting expense
expense=df[df['type']=="Expense"]
expense.head()

   id       date     type       category  amount     description
1   2 2026-09-02  Expense           Food     250           Lunch
2   3 2026-09-03  Expense         Travel     500  Cab to college
3   4 2026-09-04  Expense       Shopping    1200         Clothes
4   5 2026-09-05  Expense           Food     180       Breakfast
5   6 2026-09-06  Expense  Entertainment     350           Movie

In [71]:
# Calculate spending for each day
spending_per_day = expense.groupby('date')['amount'].sum().reset_index()
spending_per_day.head()

        date  amount
0 2026-09-02     250
1 2026-09-03     500
2 2026-09-04    1200
3 2026-09-05     180
4 2026-09-06     350

In [72]:
# Rename the column
daily_expenses = spending_per_day.rename(columns={"amount": "daily_expense"})
daily_expenses.head()

        date  daily_expense
0 2026-09-02            250
1 2026-09-03            500
2 2026-09-04           1200
3 2026-09-05            180
4 2026-09-06            350

In [73]:
# Find the highest spending day

highest_spending_day = daily_expenses["daily_expense"].idxmax()

print("Highest Spending Day:")
print(daily_expenses.loc[highest_spending_day])

Highest Spending Day:
date             2026-10-18 00:00:00
daily_expense                   1800
Name: 34, dtype: object

In [74]:
#  Average Daily Spending
avg_daily_spending = daily_expenses['daily_expense'].mean()
print("Average Daily Spending:", round(avg_daily_spending),2)

Average Daily Spending: 522 2

In [75]:
# Transactions per day
daily_transactions = (
    expense.groupby("date")
    .size()
    .reset_index(name="transaction_count")
)

daily_transactions.head()

        date  transaction_count
0 2026-09-02                  1
1 2026-09-03                  1
2 2026-09-04                  1
3 2026-09-05                  1
4 2026-09-06                  1

In [76]:
# combine both analysis
daily_summary = pd.merge(
    daily_expenses,
    daily_transactions,
    on="date"
)

daily_summary.head()

        date  daily_expense  transaction_count
0 2026-09-02            250                  1
1 2026-09-03            500                  1
2 2026-09-04           1200                  1
3 2026-09-05            180                  1
4 2026-09-06            350                  1

In [77]:
#  short by higest spending
daily_summary = daily_summary.sort_values(
    by="daily_expense",
    ascending=False
)

daily_summary.head(10)

         date  daily_expense  transaction_count
34 2026-10-18           1800                  1
20 2026-09-27           1500                  1
47 2026-11-06           1300                  1
2  2026-09-04           1200                  1
26 2026-10-05           1100                  1
42 2026-10-30            950                  1
11 2026-09-14            900                  1
46 2026-11-05            900                  1
25 2026-10-04            850                  1
51 2026-11-12            800                  1

In [78]:
highest_spending_day = daily_summary.iloc[0]

print("Daily Spending Insights")
print("-----------------------")

print(
    f"Highest spending day: "
    f"{highest_spending_day['date'].date()}"
)

print(
    f"Amount spent: "
    f"₹{highest_spending_day['daily_expense']}"
)

print(
    f"Transactions on that day: "
    f"{highest_spending_day['transaction_count']}"
)

print(
    f"Average daily spending: "
    f"₹{round(avg_daily_spending, 2)}"
)

Daily Spending Insights
-----------------------
Highest spending day: 2026-10-18
Amount spent: ₹1800
Transactions on that day: 1
Average daily spending: ₹522.22