In [6]:
# Load dataset

!git clone https://github.com/1-aditya-singh/personal-finance-intelligence-system.git

import pandas as pd
df = pd.read_csv("personal-finance-intelligence-system/data/transactions.csv")

fatal: destination path 'personal-finance-intelligence-system' already exists and is not an empty directory.

In [11]:
# Convert date column to datetime

df['date'].head()
df.dtypes
df['date']=df['date'].astype('datetime64[ns]')
df.dtypes

id                      int64
date           datetime64[ns]
type                   object
category               object
amount                  int64
description            object
dtype: object

In [15]:
# Extract month

df["month"] = df["date"].dt.to_period("M")
df[["date", "month"]].head()

        date    month
0 2026-09-01  2026-09
1 2026-09-02  2026-09
2 2026-09-03  2026-09
3 2026-09-04  2026-09
4 2026-09-05  2026-09

In [30]:
# calculate monthely income
print(df.head())
income=df[df['type']=='Income']
monthly_income=income.groupby('month')['amount'].sum()
monthly_income

   id       date     type  category  amount     description    month
0   1 2026-09-01   Income    Salary   30000  Monthly salary  2026-09
1   2 2026-09-02  Expense      Food     250           Lunch  2026-09
2   3 2026-09-03  Expense    Travel     500  Cab to college  2026-09
3   4 2026-09-04  Expense  Shopping    1200         Clothes  2026-09
4   5 2026-09-05  Expense      Food     180       Breakfast  2026-09

month
2026-09    35000
2026-10    33500
2026-11    34500
Freq: M, Name: amount, dtype: int64

In [31]:
# Monthly expenses

expense = df[df["type"] == "Expense"]

monthly_expense = expense.groupby("month")["amount"].sum()

monthly_expense

month
2026-09    10870
2026-10    11600
2026-11     5730
Freq: M, Name: amount, dtype: int64

In [32]:
# Create monthly summary

monthly_summary = pd.DataFrame({
    "income": monthly_income,
    "expense": monthly_expense
})
monthly_summary

         income  expense
month
2026-09   35000    10870
2026-10   33500    11600
2026-11   34500     5730

In [34]:
# Calculate savings

monthly_summary["savings"] = (
    monthly_summary["income"]
    - monthly_summary["expense"]
)
monthly_summary

         income  expense  savings
month
2026-09   35000    10870    24130
2026-10   33500    11600    21900
2026-11   34500     5730    28770

In [35]:
# Calculate savings rate

monthly_summary["savings_rate"] = (
    monthly_summary["savings"]
    / monthly_summary["income"]
) * 100
monthly_summary

         income  expense  savings  savings_rate
month
2026-09   35000    10870    24130     68.942857
2026-10   33500    11600    21900     65.373134
2026-11   34500     5730    28770     83.391304

In [37]:
# Round savings rate

monthly_summary["savings_rate"] = (
    monthly_summary["savings_rate"].round(2)
)

In [38]:
# Display result
monthly_summary

         income  expense  savings  savings_rate
month
2026-09   35000    10870    24130         68.94
2026-10   33500    11600    21900         65.37
2026-11   34500     5730    28770         83.39

In [50]:
# month with highest expenses

highest_expense_month = monthly_summary["expense"].idxmax()

print("Highest Expense Month:", highest_expense_month)
print("Expense:", monthly_summary.loc[highest_expense_month, "expense"]).

Highest Expense Month: 2026-10
Expense: 11600

In [51]:
# month with higest savings
highest_saving_month = monthly_summary["savings"].idxmax()

print("Highest Saving Month:", highest_saving_month)
print("Savings:", monthly_summary.loc[highest_saving_month, "savings"])

Highest Saving Month: 2026-11
Savings: 28770

In [52]:
# highest saving rates
best_saving_rate_month = monthly_summary["savings_rate"].idxmax()

print("Best Savings Rate Month:", best_saving_rate_month)
print(
    "Savings Rate:",
    monthly_summary.loc[best_saving_rate_month, "savings_rate"],
    "%"
)

Best Savings Rate Month: 2026-11
Savings Rate: 83.39 %

In [53]:
# Financial Insights

highest_expense_month = monthly_summary["expense"].idxmax()
highest_saving_month = monthly_summary["savings"].idxmax()
best_saving_rate_month = monthly_summary["savings_rate"].idxmax()

print("Financial Insights")
print("------------------")

print(
    f"Highest spending month: {highest_expense_month}"
)

print(
    f"Highest savings month: {highest_saving_month}"
)

print(
    f"Best savings rate: {best_saving_rate_month}"
)

Financial Insights
------------------
Highest spending month: 2026-10
Highest savings month: 2026-11
Best savings rate: 2026-11

In [56]:
# Average monthly expense
average_monthly_expense = monthly_summary["expense"].mean()

print(
    "Average Monthly Expense:",
    round(average_monthly_expense, 2)
)

Average Monthly Expense: 9400.0