In [3]:
# Load dataset

!git clone https://github.com/1-aditya-singh/personal-finance-intelligence-system.git

fatal: destination path 'personal-finance-intelligence-system' already exists and is not an empty directory.

In [4]:
# Load dataset
import pandas as pd
df=pd.read_csv("personal-finance-intelligence-system/data/transactions.csv")
df.head()

   id        date     type  category  amount     description
0   1  2026-09-01   Income    Salary   30000  Monthly salary
1   2  2026-09-02  Expense      Food     250           Lunch
2   3  2026-09-03  Expense    Travel     500  Cab to college
3   4  2026-09-04  Expense  Shopping    1200         Clothes
4   5  2026-09-05  Expense      Food     180       Breakfast

In [6]:
# separate income and expense
income = df[df["type"] == "Income"]
expenses = df[df["type"] == "Expense"]

In [7]:
# total income
total_income = income["amount"].sum()

print("Total Income:", total_income)

Total Income: 103000

In [9]:
# total expense
total_expense = expenses["amount"].sum()

print("Total Expense:", total_expense)

Total Expense: 28200

In [10]:
# total saving
savings = total_income - total_expense

print("Total Savings:", savings)

Total Savings: 74800

In [13]:
# Calculate overall savings rate
savings_rate = (savings / total_income) * 100

print("Savings Rate:", round(savings_rate, 2), "%")

Savings Rate: 72.62 %

In [21]:
# Monthly Income and Expense
df["date"] = pd.to_datetime(df["date"])
df["month"] = df["date"].dt.to_period("M")

# monthly income
monthly_income = df[df["type"]=='Income'].groupby("month")['amount'].sum()

# monthly expense
monthly_expense = df[df["type"]=='Expense'].groupby("month")['amount'].sum()

In [24]:
# monthly saving table
monthly_savings = pd.DataFrame({
    "income": monthly_income,
    "expense": monthly_expense
})
monthly_savings

         income  expense
month
2026-09   35000    10870
2026-10   33500    11600
2026-11   34500     5730

In [26]:
# monthly saving
monthly_savings["savings"] = (
    monthly_savings["income"]
    - monthly_savings["expense"]
)

In [27]:
# monthly saving rate
monthly_savings["savings_rate"] = (
    monthly_savings["savings"]
    / monthly_savings["income"]
) * 100

In [30]:
# best saving month
best_saving_month = monthly_savings["savings"].idxmax()

print("Best Saving Month:", best_saving_month)

# to get actual amount
best_saving_amount = monthly_savings.loc[
    best_saving_month,
    "savings"
]

print("Best Saving Amount: ₹", best_saving_amount)

Best Saving Month: 2026-11
Best Saving Amount: ₹ 28770

In [31]:
#  lowest saving month
lowest_saving_month = monthly_savings["savings"].idxmin()

print("Lowest Saving Month:", lowest_saving_month)

lowest_saving_amount = monthly_savings.loc[
    lowest_saving_month,
    "savings"
]

print("Lowest Saving Amount: ₹", lowest_saving_amount)

Lowest Saving Month: 2026-10
Lowest Saving Amount: ₹ 21900

In [32]:
# average monthly saving
average_monthly_savings = monthly_savings["savings"].mean()

print(
    "Average Monthly Savings: ₹",
    round(average_monthly_savings, 2)
)

Average Monthly Savings: ₹ 24933.33

In [33]:
# average saving rate
average_savings_rate = monthly_savings["savings_rate"].mean()

print(
    "Average Monthly Savings Rate:",
    round(average_savings_rate, 2),
    "%"
)

Average Monthly Savings Rate: 72.57 %

In [34]:
print("Savings Analysis Report")
print("-----------------------")

print(f"Total Income: ₹{total_income}")
print(f"Total Expense: ₹{total_expense}")
print(f"Total Savings: ₹{savings}")
print(f"Overall Savings Rate: {round(savings_rate, 2)}%")

print(
    f"Average Monthly Savings: "
    f"₹{round(average_monthly_savings, 2)}"
)

print(
    f"Average Monthly Savings Rate: "
    f"{round(average_savings_rate, 2)}%"
)

print(
    f"Best Saving Month: "
    f"{best_saving_month}"
)

print(
    f"Best Saving Amount: "
    f"₹{best_saving_amount}"
)

print(
    f"Lowest Saving Month: "
    f"{lowest_saving_month}"
)

print(
    f"Lowest Saving Amount: "
    f"₹{lowest_saving_amount}"
)

Savings Analysis Report
-----------------------
Total Income: ₹103000
Total Expense: ₹28200
Total Savings: ₹74800
Overall Savings Rate: 72.62%
Average Monthly Savings: ₹24933.33
Average Monthly Savings Rate: 72.57%
Best Saving Month: 2026-11
Best Saving Amount: ₹28770
Lowest Saving Month: 2026-10
Lowest Saving Amount: ₹21900

In [36]:
best_rate_month = monthly_savings["savings_rate"].idxmax()

best_rate = monthly_savings.loc[
    best_rate_month,
    "savings_rate"
]

print(
    f"Best savings rate was in {best_rate_month} "
    f"at {best_rate}%."
)

difference = best_saving_amount - lowest_saving_amount

print(
    f"Savings difference between best and lowest month: "
    f"₹{difference}"
)

Best savings rate was in 2026-11 at 83.3913043478261%.
Savings difference between best and lowest month: ₹6870