In [2]:
# Load dataset

!git clone https://github.com/Aadi22204/personal-finance-intelligence.git

fatal: destination path 'personal-finance-intelligence' already exists and is not an empty directory.

In [4]:
#  Load dataset
import pandas as pd
df=pd.read_csv("personal-finance-intelligence/data/transactions.csv")
df.head()

   id        date     type  category  amount     description
0   1  2026-09-01   Income    Salary   30000  Monthly salary
1   2  2026-09-02  Expense      Food     250           Lunch
2   3  2026-09-03  Expense    Travel     500  Cab to college
3   4  2026-09-04  Expense  Shopping    1200         Clothes
4   5  2026-09-05  Expense      Food     180       Breakfast

In [8]:
#  Convert date column
df['date']=pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           60 non-null     int64
 1   date         60 non-null     datetime64[ns]
 2   type         60 non-null     object
 3   category     60 non-null     object
 4   amount       60 non-null     int64
 5   description  60 non-null     object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 2.9+ KB

In [10]:
# Select expense
expense=df[df['type']=='Expense']
expense.head()

   id       date     type       category  amount     description
1   2 2026-09-02  Expense           Food     250           Lunch
2   3 2026-09-03  Expense         Travel     500  Cab to college
3   4 2026-09-04  Expense       Shopping    1200         Clothes
4   5 2026-09-05  Expense           Food     180       Breakfast
5   6 2026-09-06  Expense  Entertainment     350           Movie

In [12]:
# Total expense transactions
total_expense_transactions=len(expense)
print("Total Expense Transactions:", total_expense_transactions)

Total Expense Transactions: 54

In [14]:
# Average expense transaction
average_expense=expense['amount'].mean()
print("Average Expense Transaction:", round(average_expense, 2))

Average Expense Transaction: 522.22

In [18]:
# Find the largest single expense
largest_expense=expense['amount'].max()
print("Largest Single Expense:", largest_expense)

Largest Single Expense: 1800

In [20]:
# Find the smallest expense
smallest_expense=expense['amount'].min()
print("Smallest Expense:", smallest_expense)

Smallest Expense: 150

In [22]:
# Calculate median expense
median_expense = expense["amount"].median()

print("Median Expense:", median_expense)

Median Expense: 400.0

In [23]:
# find the most frequent expense category
category_transaction_count = (
    expense["category"]
    .value_counts()
)

print(category_transaction_count)

category
Food             18
Travel           10
Shopping          7
Entertainment     6
Bills             5
Education         5
Health            3
Name: count, dtype: int64

In [26]:
# Find the most frequent category
expense.head()
most_frequent_category = category_transaction_count.idxmax()

print("Most Frequent Expense Category:", most_frequent_category)

Most Frequent Expense Category: Food

In [29]:
# Find the category with the highest total spending
category_spending = (
    expense.groupby("category")["amount"]
    .sum()
    .sort_values(ascending=False)
)

print(category_spending)

category
Shopping         8750
Food             4500
Travel           4250
Bills            3800
Education        2700
Entertainment    2250
Health           1950
Name: amount, dtype: int64

In [28]:
print("Spending Behavior Summary")
print("-------------------------")

print(
    f"Total expense transactions: "
    f"{total_expense_transactions}"
)

print(
    f"Average expense per transaction: "
    f"₹{round(average_expense, 2)}"
)

print(
    f"Median expense: "
    f"₹{median_expense}"
)

print(
    f"Largest single expense: "
    f"₹{largest_expense}"
)

print(
    f"Smallest expense: "
    f"₹{smallest_expense}"
)

print(
    f"Most frequent category: "
    f"{most_frequent_category}"
)

print(
    f"Highest spending category: "
    f"{category_spending.index[0]}"
)

Spending Behavior Summary
-------------------------
Total expense transactions: 54
Average expense per transaction: ₹522.22
Median expense: ₹400.0
Largest single expense: ₹1800
Smallest expense: ₹150
Most frequent category: Food
Highest spending category: Shopping