In [2]:
# Load dataset

!git clone https://github.com/Aadi22204/personal-finance-intelligence.git

fatal: destination path 'personal-finance-intelligence' already exists and is not an empty directory.

In [3]:
# Load dataset
import pandas as pd
df=pd.read_csv("personal-finance-intelligence/data/transactions.csv")
df.head()

   id        date     type  category  amount     description
0   1  2026-09-01   Income    Salary   30000  Monthly salary
1   2  2026-09-02  Expense      Food     250           Lunch
2   3  2026-09-03  Expense    Travel     500  Cab to college
3   4  2026-09-04  Expense  Shopping    1200         Clothes
4   5  2026-09-05  Expense      Food     180       Breakfast

In [7]:
# Select expenses
expenses=df[df['type']=='Expense'].copy()
expenses.head()

   id        date     type       category  amount     description
1   2  2026-09-02  Expense           Food     250           Lunch
2   3  2026-09-03  Expense         Travel     500  Cab to college
3   4  2026-09-04  Expense       Shopping    1200         Clothes
4   5  2026-09-05  Expense           Food     180       Breakfast
5   6  2026-09-06  Expense  Entertainment     350           Movie

In [8]:
#  high expense alert
average_expense = expenses["amount"].mean()

high_expense_limit = average_expense * 2

print("Average Expense:", round(average_expense, 2))
print("High Expense Limit:", round(high_expense_limit, 2))

Average Expense: 522.22
High Expense Limit: 1044.44

In [10]:
# Find high expenses
high_expenses = expenses[
    expenses["amount"] > high_expense_limit
]
high_expenses[
    ["date", "category", "amount", "description"]
]

          date  category  amount  description
3   2026-09-04  Shopping    1200      Clothes
22  2026-09-27  Shopping    1500     Backpack
29  2026-10-05  Shopping    1100      Clothes
38  2026-10-18  Shopping    1800  Electronics
52  2026-11-06  Shopping    1300      Clothes

In [11]:
# High Category Spending
category_spending = expenses.groupby('category')['amount'].sum().sort_values(ascending=False)
category_spending

category
Shopping         8750
Food             4500
Travel           4250
Bills            3800
Education        2700
Entertainment    2250
Health           1950
Name: amount, dtype: int64

In [13]:
# Set a category alert threshold
category_alert_limit = 5000
high_spending_categories = category_spending[
    category_spending > category_alert_limit
]
print("High Spending Categories")
print("------------------------")

print(high_spending_categories)

High Spending Categories
------------------------
category
Shopping    8750
Name: amount, dtype: int64

In [15]:
# Frequent Spending
category_transaction_count = (
    expenses["category"]
    .value_counts()
)

category_transaction_count

transaction_alert_limit = 10
frequent_categories = category_transaction_count[
    category_transaction_count > transaction_alert_limit
]

print("Frequent Spending Categories")
print("----------------------------")

print(frequent_categories)

Frequent Spending Categories
----------------------------
category
Food    18
Name: count, dtype: int64

In [16]:
print("Financial Spending Alerts")
print("-------------------------")

if len(high_expenses) > 0:
    print(
        f"🔴 High Expense Alert: "
        f"{len(high_expenses)} transaction(s) above "
        f"₹{round(high_expense_limit, 2)}"
    )
else:
    print("✅ No unusually high expenses detected.")


if len(high_spending_categories) > 0:
    print(
        f"🟠 Category Alert: "
        f"{len(high_spending_categories)} category/categories "
        f"above ₹{category_alert_limit}"
    )
else:
    print("✅ No high-spending categories detected.")


if len(frequent_categories) > 0:
    print(
        f"🟡 Frequency Alert: "
        f"{len(frequent_categories)} category/categories "
        f"with more than {transaction_alert_limit} transactions"
    )
else:
    print("✅ No unusually frequent spending categories detected.")

Financial Spending Alerts
-------------------------
🔴 High Expense Alert: 5 transaction(s) above ₹1044.44
🟠 Category Alert: 1 category/categories above ₹5000
🟡 Frequency Alert: 1 category/categories with more than 10 transactions