In [2]:
# Load dataset

!git clone https://github.com/Aadi22204/personal-finance-intelligence.git

fatal: destination path 'personal-finance-intelligence' already exists and is not an empty directory.

In [4]:
# Load dataset
import pandas as pd
df=pd.read_csv("personal-finance-intelligence/data/transactions.csv")
df.head()

   id        date     type  category  amount     description
0   1  2026-09-01   Income    Salary   30000  Monthly salary
1   2  2026-09-02  Expense      Food     250           Lunch
2   3  2026-09-03  Expense    Travel     500  Cab to college
3   4  2026-09-04  Expense  Shopping    1200         Clothes
4   5  2026-09-05  Expense      Food     180       Breakfast

In [5]:
# convert date
df['date']=pd.to_datetime(df['date'])

In [6]:
# selecte expense
expense=df[df['type']=='Expense']
expense.head()

   id       date     type       category  amount     description
1   2 2026-09-02  Expense           Food     250           Lunch
2   3 2026-09-03  Expense         Travel     500  Cab to college
3   4 2026-09-04  Expense       Shopping    1200         Clothes
4   5 2026-09-05  Expense           Food     180       Breakfast
5   6 2026-09-06  Expense  Entertainment     350           Movie

In [7]:
# Sort expenses from largest to smallest
top_expenses=expense.sort_values(by='amount',ascending=False)
top_expenses.head(10)

    id       date     type  category  amount       description
38  39 2026-10-18  Expense  Shopping    1800       Electronics
22  23 2026-09-27  Expense  Shopping    1500          Backpack
52  53 2026-11-06  Expense  Shopping    1300           Clothes
3    4 2026-09-04  Expense  Shopping    1200           Clothes
29  30 2026-10-05  Expense  Shopping    1100           Clothes
46  47 2026-10-30  Expense  Shopping     950           Clothes
12  13 2026-09-14  Expense  Shopping     900             Shoes
51  52 2026-11-05  Expense     Bills     900  Electricity bill
28  29 2026-10-04  Expense     Bills     850  Electricity bill
56  57 2026-11-12  Expense    Health     800  Medical expenses

In [8]:
# Display Top 5 expenses
top_5_expenses = top_expenses.head(5)

top_5_expenses

    id       date     type  category  amount  description
38  39 2026-10-18  Expense  Shopping    1800  Electronics
22  23 2026-09-27  Expense  Shopping    1500     Backpack
52  53 2026-11-06  Expense  Shopping    1300      Clothes
3    4 2026-09-04  Expense  Shopping    1200      Clothes
29  30 2026-10-05  Expense  Shopping    1100      Clothes

In [9]:
# Calculate the total of Top 5 expenses
top_5_total = top_5_expenses["amount"].sum()

print("Top 5 Expenses Total:", top_5_total)

Top 5 Expenses Total: 6900

In [11]:
# Compare Top 5 with total expenses
total_expenses = expense["amount"].sum()

print("Total Expenses:", total_expenses)

top_5_percentage = (
    top_5_total / total_expenses
) * 100

print(
    "Top 5 Expenses Percentage:",
    round(top_5_percentage, 2),
    "%"
)

Total Expenses: 28200
Top 5 Expenses Percentage: 24.47 %

In [20]:
# Find the largest expense category among Top 5
top_5_categories = top_5_expenses["category"].value_counts()

print(top_5_categories)

most_common_top_category = top_5_categories.idxmax()

print(
    "Most Common Category in Top 5:",
    most_common_top_category
)

category
Shopping    5
Name: count, dtype: int64
Most Common Category in Top 5: Shopping

In [13]:
# Find the largest expense transaction
largest_transaction = top_expenses.iloc[0]

print("Largest Expense Transaction")
print("---------------------------")
print(largest_transaction)

Largest Expense Transaction
---------------------------
id                              39
date           2026-10-18 00:00:00
type                       Expense
category                  Shopping
amount                        1800
description            Electronics
Name: 38, dtype: object

In [14]:
# Create a clean Top 5 table
top_5_clean = top_5_expenses[
    ["date", "category", "amount", "description"]
]

top_5_clean

         date  category  amount  description
38 2026-10-18  Shopping    1800  Electronics
22 2026-09-27  Shopping    1500     Backpack
52 2026-11-06  Shopping    1300      Clothes
3  2026-09-04  Shopping    1200      Clothes
29 2026-10-05  Shopping    1100      Clothes

In [21]:
print("Top Expense Insights")
print("--------------------")

print(
    f"Largest single expense: "
    f"₹{largest_transaction['amount']}"
)

print(
    f"Category: "
    f"{largest_transaction['category']}"
)

print(
    f"Date: "
    f"{largest_transaction['date'].date()}"
)

print(
    f"Top 5 expenses total: "
    f"₹{top_5_total}"
)

print(
    f"Top 5 expenses represent: "
    f"{round(top_5_percentage, 2)}% of total spending"
)

print(
    f"Most common category among Top 5: "
    f"{most_common_top_category}"
)

Top Expense Insights
--------------------
Largest single expense: ₹1800
Category: Shopping
Date: 2026-10-18
Top 5 expenses total: ₹6900
Top 5 expenses represent: 24.47% of total spending
Most common category among Top 5: Shopping